### ISSUE TITLE
RelativeTimestamps: Option to not display seconds?

### ISSUE THREAD

**Issue by edemaine** [BrandonXLF/BetterDiscordPlugins#1]
Would it be possible to add an option to not display the number of seconds?  I like seeing the relative times, but it's constantly refreshing, so only giving minute resolution would reduce the "flicker".

If you'd rather, I could try to write a PR.

**Comment by BrandonXLF** [comment]
Yeah, I can add that. I'm thinking that option should remove seconds from the relative timestamp in the message timestamp, but not from the one in the tooltip. This would leave a way to see seconds with the option enabled while avoiding the constant refreshing. Is that fine with you?

**Comment by edemaine** [comment]
Yep, that sounds perfect! I think when hovering it makes sense to show all the information in the tooltip in any case.

**Comment by BrandonXLF** [comment]
Yeah, that's what I thought. I'll add the setting later today.

**Comment by edemaine** [comment]
New release looks great — thanks for the lovely plugin!
