### ISSUE TITLE
Does't work since the last Discord update

### ISSUE THREAD

**Issue by Pharaoh2k** [BrandonXLF/BetterDiscordPlugins#8]
Plugin no longer works since the last discord update.

**Comment by BrandonXLF** [comment]
Fixed by 24cbd9b2a05c4d703494ee103c38440727305c02. Also make sure you are using the latest version of [0PluginLibrary.plugin.js](https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js). 

Let me know if you encounter any more issues.
