### ISSUE TITLE
KeepCurrentChannel crashes discord

### ISSUE THREAD

**Issue by TheGreatTaz** [BrandonXLF/BetterDiscordPlugins#9]
KeepCurrentChannel crashes discord discord when switching accounts on current version

**Comment by BrandonXLF** [comment]
@TheGreatTaz Hello, and sorry for the late reply. Can you check if this issue still occurs in the latest version?

**Comment by TheGreatTaz** [comment]
yes version 1.1.2

**Comment by BrandonXLF** [comment]
@TheGreatTaz Can you try disabling all other plugins and see if the issue persists?

**Comment by TheGreatTaz** [comment]
sorry about the long response time
somehow the big update (the one that broke almost every plugin) has fixed my issue
